# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: microdrop-3-unstable
  version: {{ MICRODROP_VERSION }}

build:
  script_env:
    MICRODROP_VERSION
  number: 0

requirements:
  build:
    - nodejs >=8.2.1
  run:
    - nodejs >=8.2.1

about:
  home: https://github.com/sci-bots/microdrop-3.0
  license: GPL
